### ISSUE TITLE
Converting images from .docx to .adoc

### ISSUE THREAD

**Issue by anermina** [metanorma/reverse_adoc#30]
I tried to convert the "EDITING GUIDELINES" recommendation (#20) using the command that includes conversion of external images:
w2a .\reference-docs\T-Editing-Guidelines-201602.docx -o TEG.adoc -e

However, I wasn't able to convert it due to the following error:
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/reverse_adoc-0.2.3/lib/reverse_asciidoctor/converters/img.rb:21:in `datauri2file': uninitialized constant ReverseAsciidoctor::Converters::Img::Pathname (NameError)

By now, I've been working on a document without the images (converted without using -e in command) and didn't manage to figure out yet how to convert the images as well. Can you please give me some instructions?

**Comment by opoudjis** [comment]
This is odd. Pathname is a standard library function, but apparently it still needs a library import on your Ruby; it didn't on mine (and it didn't on the markdown gem I based this on). OK, I will do an update of the gem.
