### ISSUE TITLE
Macos libreoffice tests hang

### ISSUE THREAD

**Issue by w00lf** [metanorma/reverse_adoc#41]
Currently, we have gem `word-to-markdown` that uses `soffice` binary to convert docx docx to adoc, its libreoffice tool so in order to test it properly in ci it need to be installed and configured. On macos one can install libreoffice by using `brew cask install libreoffice`, however, after such install any run of `soffice` cli tool leads to hanging of the github action workflow, i was not been able to determine why it is happening, here is an example of such run - https://github.com/metanorma/reverse_adoc/commit/181683de8a5b58c1b8fab4b0588de3d008b780d0/checks?check_suite_id=354847489, job stopped on soffice cli tool run and was killed by github after 6 hours.

**Comment by ronaldtse** [comment]
Works perfectly as of https://github.com/metanorma/reverse_adoc/runs/840038506?check_suite_focus=true . Closing!
