### ISSUE TITLE
Why <math> element handler removes double round brackets?

### ISSUE THREAD

**Issue by skalee** [metanorma/reverse_adoc#67]
See line 13 in `<math>` element converter:

https://github.com/metanorma/reverse_adoc/blob/99ec3a1164289f9fc2736d770406d9b09e20f787/lib/reverse_adoc/converters/math.rb#L10-L15

Last `#gsub` call in that line replaces doubled round brackets (like in `((...))`) with single ones (`(...)`). What's the reason for doing that? Although it seems not very harmful, it actually changes the expression itself and the way it is rendered with MathJax. For example:

![Zrzut ekranu 2021-04-28 o 05 08 50](https://user-images.githubusercontent.com/154287/116341249-d9970c80-a7e0-11eb-9f80-9f23fd93d645.png)
![Zrzut ekranu 2021-04-28 o 05 09 00](https://user-images.githubusercontent.com/154287/116341253-db60d000-a7e0-11eb-96b8-72afab72bb4e.png)
 
@opoudjis, this change was made by you 3 years ago in https://github.com/metanorma/reverse_adoc/commit/e16d77d72ee341a288a908e3be6c860273b0fa7c, do you remember why?

**Comment by opoudjis** [comment]
I don't, but you should not trust the MathML generated by Microsoft's XSLT (exported from source OOXML). I would not at all be surprised if Microsoft's XSLT overgenerates brackets, and I clamped down on it doing so in response three years ago.

I'd trial it with some actual Word exports before commiting any such change if I were you.

**Comment by skalee** [comment]
Okay. I'll make it optional if I stumble upon any issues caused by this thing.
