### ISSUE TITLE
Option to extract images to separate files on conversion

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/reverse_adoc#86]
In:
* https://github.com/metanorma/mn-samples-mlit/issues/1

We encountered a 50MB HTML file with images encoded in Data URIs over >400 images. This led to a very tedious task in extracting images manually.

We need reverse_adoc to do this automatically.

**Comment by hmdne** [comment]
Solved by #35 ?

**Comment by ronaldtse** [comment]
@hmdne maybe… but I think the new HTML document uses webp images, I’m not sure if it’s supported?

**Comment by hmdne** [comment]
@ronaldtse I added a test to confirm this functionality works.
